"""Write the 5 host hook scripts under <home>/.betterai/hooks/.

WHY fail-open here when the server is fail-hard everywhere: these shims
run inside the user's coding-agent session. If the BetterAI server is
down, a hard-failing hook would brick every prompt and every tool call
of the client -- exactly the "gates brick sessions" risk in the plan.
So transport errors swallow to `|| true` and exit 0; gating only ever
happens on an explicit `"block": true` answer from the server (exit 2).
"""

from __future__ import annotations

from pathlib import Path

from app.installer.install_env import MCP_PORT, betterai_root

HOOK_NAMES = (
    "user-prompt-submit",
    "pre-tool-use",
    "post-tool-use",
    "stop",
    "session-end",
)

_SCRIPT_TEMPLATE = """#!/usr/bin/env bash
# BetterAI host hook: {name} (generated by `betterai install`).
# Fail-open on transport errors: an unreachable server must never brick
# the client session. Blocks only on an explicit "block": true response.
set -u
BETTERAI_HOME="${{BETTERAI_HOME:-$HOME/.betterai}}"
TOKEN_FILE="$BETTERAI_HOME/token"
PAYLOAD="$(cat)"
RESPONSE="$(curl -s -X POST \\
  -H "Authorization: Bearer $(cat "$TOKEN_FILE" 2>/dev/null)" \\
  -H "content-type: application/json" \\
  --data "$PAYLOAD" \\
  "http://127.0.0.1:{port}/hooks/{name}" 2>/dev/null || true)"
if [ -n "$RESPONSE" ]; then
  printf '%s\\n' "$RESPONSE"
fi
case "$RESPONSE" in
  *'"block": true'* | *'"block":true'*) exit 2 ;;
esac
exit 0
"""


def write_hook_scripts(home: str) -> list[str]:
    """Write all five scripts, mode 0755; returns the written paths."""
    hooks_dir = Path(betterai_root(home)) / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for name in HOOK_NAMES:
        path = hooks_dir / name
        path.write_text(_SCRIPT_TEMPLATE.format(name=name, port=MCP_PORT))
        path.chmod(0o755)
        written.append(str(path))
    return written
