"""Write <home>/.betterai/bin/betterai-mcp-stdio: the stdio bridge.

WHY a bridge at all: the server speaks Streamable HTTP only (rule:
no-stdio-mcp-transport), but some MCP clients can only spawn stdio
servers. Supergateway translates stdio <-> Streamable HTTP in a
throwaway container. The bearer token is read at invocation time via
command substitution -- never embedded in the script -- so rotating the
token never requires reinstalling and no secret sits in any config.
"""

from __future__ import annotations

from pathlib import Path

from app.installer.install_env import MCP_PORT, SUPERGATEWAY_IMAGE, betterai_root

_SCRIPT = f"""#!/usr/bin/env bash
# BetterAI stdio -> Streamable-HTTP bridge (generated by `betterai install`).
set -eu
BETTERAI_HOME="${{BETTERAI_HOME:-$HOME/.betterai}}"
exec docker run -i --rm --add-host=host.docker.internal:host-gateway {SUPERGATEWAY_IMAGE} \\
  --streamableHttp "http://host.docker.internal:{MCP_PORT}/mcp" \\
  --oauth2Bearer "$(cat "$BETTERAI_HOME/token")" \\
  --logLevel none
"""


def bridge_path(home: str) -> str:
    return str(Path(betterai_root(home)) / "bin" / "betterai-mcp-stdio")


def write_bridge(home: str) -> str:
    """Write the bridge script, mode 0755; returns its path."""
    path = Path(bridge_path(home))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_SCRIPT)
    path.chmod(0o755)
    return str(path)
